// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _418FinalProject.Models;

namespace _418FinalProject.Migrations
{
    [DbContext(typeof(DataBankContext))]
    [Migration("20190501151817_User")]
    partial class User
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("_418FinalProject.Models.Question", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Question ID");

                    b.Property<string>("Answer1Text")
                        .IsRequired()
                        .HasColumnName("ANS1")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Answer2Text")
                        .IsRequired()
                        .HasColumnName("ANS2")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Answer3Text")
                        .IsRequired()
                        .HasColumnName("ANS3")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Answer4Text")
                        .IsRequired()
                        .HasColumnName("ANS4")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Image")
                        .HasColumnName("Image")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnName("Question Text")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("TestID");

                    b.Property<bool>("TrueFalse")
                        .HasColumnName("True False")
                        .HasColumnType("bit");

                    b.HasKey("QuestionID");

                    b.HasIndex("TestID");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("_418FinalProject.Models.Test", b =>
                {
                    b.Property<int>("TestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<string>("TestTitle")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("TestID");

                    b.ToTable("Test");
                });

            modelBuilder.Entity("_418FinalProject.Models.Test_Titles", b =>
                {
                    b.Property<int>("Test_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Test_ID");

                    b.ToTable("Test_Titles");
                });

            modelBuilder.Entity("_418FinalProject.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("USER_ID");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("PASSWORD")
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("Type")
                        .HasColumnName("ADMIN")
                        .HasColumnType("BIT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnName("USER_NAME")
                        .HasColumnType("varchar(20)");

                    b.HasKey("UserID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("_418FinalProject.Models.Question", b =>
                {
                    b.HasOne("_418FinalProject.Models.Test")
                        .WithMany("Questions")
                        .HasForeignKey("TestID");
                });
#pragma warning restore 612, 618
        }
    }
}
