// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _418FinalProject.Models;

namespace _418FinalProject.Migrations
{
    [DbContext(typeof(DataBankContext))]
    [Migration("20190424214650_TestTables")]
    partial class TestTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("_418FinalProject.Models.Question", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Question_ID");

                    b.Property<string>("Answer1Text")
                        .IsRequired()
                        .HasColumnName("ANS1")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Answer2Text")
                        .IsRequired()
                        .HasColumnName("ANS2")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Answer3Text")
                        .IsRequired()
                        .HasColumnName("ANS3")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Answer4Text")
                        .IsRequired()
                        .HasColumnName("ANS4")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Image")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnName("Question_Text")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<byte>("TrueFalse")
                        .HasColumnName("True_False")
                        .HasColumnType("bit");

                    b.HasKey("QuestionID");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("_418FinalProject.Models.Test_Titles", b =>
                {
                    b.Property<int>("Test_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Test_ID");

                    b.ToTable("Test_Titles");
                });

            modelBuilder.Entity("_418FinalProject.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("USER_NAME")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("PASSWORD")
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("Type")
                        .HasColumnName("ADMIN")
                        .HasColumnType("BIT");

                    b.HasKey("Username");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
