// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _418FinalProject.Models;

namespace _418FinalProject.Migrations
{
    [DbContext(typeof(QuesitonContext))]
    [Migration("20190418194522_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("_418FinalProject.Models.Question", b =>
                {
                    b.Property<int>("QuestionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<string>("Answer1")
                        .IsRequired()
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(100);

                    b.Property<string>("Answer1Text")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Answer2")
                        .IsRequired()
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(100);

                    b.Property<string>("Answer2Text")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Answer3")
                        .IsRequired()
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(100);

                    b.Property<string>("Answer3Text")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Answer4")
                        .IsRequired()
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(100);

                    b.Property<string>("Answer4Text")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<short>("Category")
                        .HasColumnType("smallint");

                    b.Property<string>("Image")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("QuestionNumber");

                    b.ToTable("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
